# Generated by Django 3.1.2 on 2020-10-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='vaccine date')),
                ('shot', models.CharField(choices=[('1', 'Distemper'), ('2', 'Measles'), ('3', 'Parainfluenza'), ('4', 'Bordatella'), ('5', 'Rebies')], default='1', max_length=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
